default:
  image_dir: imgs
  output_dir: output
  bucket: trolley-monitor
  readme_md: instructions.md
  camera_types: 
    - HD11
    - HD12
    - HD21
    - HD22
    - HD31
    - HD32
  camera_names: 
    - 高(左)
    - 高(右)
    - 中(左)
    - 中(右)
    - 低(左)
    - 低(右)
  trolley_ids: 
    - trolley1
    - trolley2
    - trolley3
  result_keys: 
    - ix
    - upper_boundary
    - lower_boundary
    - estimated_upper_edge
    - estimated_lower_edge
    - estimated_width
    - estimated_slope
    - estimated_upper_edge_variance
    - estimated_lower_edge_variance
    - estimated_slope_variance
    - brightness_center
    - brightness_mean
    - brightness_std
    - current_state

format_func:
  camera_name_to_type:
    高(左): HD11
    高(右): HD12
    中(左): HD21
    中(右): HD22
    低(左): HD31
    低(右): HD32
  rail_names:
    Kawagoe: 川越線
    Chuo: 中央線
    Yamate: 山手線
    Utsunomiya: 宇都宮線
  station_names:
    st: 構内
    Omiya: 大宮
    Nisshin: 日進
    Nishioomiya: 西大宮
    Sashiougi: 指扇
    Minamifuruya: 南古谷
    Tokyo: 東京
    Kanda: 神田
    Ochanomizu: 御茶ノ水
    Suidobashi: 水道橋
    Iidabashi: 飯田橋
    Ichigaya: 市ヶ谷
    Yotsuya: 四ツ谷
    Shinanomachi: 信濃町
    Sendagaya: 千駄ヶ谷
    Yoyogi: 代々木
    Shinjuku: 新宿
    Ookubo: 大久保
    Higashinakano: 東中野
    Nakano: 中野
    Koenji: 高円寺
    Asagaya: 阿佐ヶ谷
    Ogikubo: 荻窪
    Nishiogikubo: 西荻窪
    Kichijoji: 吉祥寺
    Miyahara: 宮原
    Ueno: 上野
    Nippori: 日暮里
    Tabata: 田端
    Yurakucho: 有楽町
    Shinbashi: 新橋
    Hamamatsucho: 浜松町
    Tamachi: 田町
    Shinagawa: 品川
    Oosaki: 大崎
  rail_type_names:
    up: 上り
    down: 下り
    soto: 外回り
    uchi: 内回り
  time_band_names:
    day: 昼間
    knight: 夜間


measurement:
  missing_threshold: 5
  brightness_diff_threshold: 255
  sharpness_threshold: 1
  missing_count_limit: 100

results:
  max_len: 1000