default:
  image_dir: imgs
  output_dir: output
  readme_md: 'instructions.md'
  camera_types: ['HD11', 'HD12', 'HD21', 'HD22', 'HD31', 'HD32']
  camera_names:
    HD11: 高(左)
    HD12: 高(右)
    HD21: 中(左)
    HD22: 中(右)
    HD31: 低(左)
    HD32: 低(右)
  rail_names:
    Kawagoe: 川越線
    Chuo: 中央線
    Utsunomiya: 宇都宮線
  station_names:
    Tokyo: 東京
    Kanda: 神田
    Ochanomizu: 御茶ノ水
    Suidobashi: 水道橋
    Iidabashi: 飯田橋
    Ichigaya: 市ヶ谷
    Yotsuya: 四ツ谷
    Shinanomachi: 信濃町
    Sendagaya: 千駄ヶ谷
    Yoyogi: 代々木
    Shinjuku: 新宿
    Omiya: 大宮
    Miyahara: 宮原
    Nisshin: 日進
    Nishioomiya: 西大宮
    Sashiougi: 指扇
    Minamifuruya: 南古谷
  rail_type_names:
    up: 上り
    down: 下り
  time_band_names:
    day: 昼間
    knight: 夜間

measurement:
  missing_threshold: 5
  brightness_diff_threshold: 255
  sharpness_threshold: 1
  missing_count_limit: 100