default:
  image_dir: imgs
  output_dir: output
  bucket: trolley-monitor
  readme_md: instructions.md
  camera_types: 
    - HD11
    - HD12
    - HD21
    - HD22
    - HD31
    - HD32
  camera_names: 
    - 高(左)
    - 高(右)
    - 中(左)
    - 中(右)
    - 低(左)
    - 低(右)
  trolley_ids: 
    - trolley1
    - trolley2
    - trolley3
  result_keys:
    # - ix
    - measured_upper_edge
    - measured_lower_edge
    - estimated_upper_edge
    - estimated_lower_edge
    # - estimated_width    # lower-upperで計算する
    - brightness_center
    - brightness_mean
    - brightness_std
    - estimated_slope    # pixel
    - upper_boundary    # pixel
    - lower_boundary    # pixel
    - estimated_upper_edge_variance    # kalman
    - estimated_lower_edge_variance    # kalman
    - estimated_slope_variance    # kalman
    - trolley_end_reason
    - mask_edgelog_1
    - mask_edgelog_2
    # - current_state
  result_keys_kalman:
    - ix
    - estimated_upper_edge
    - estimated_lower_edge
    - measured_upper_edge
    - measured_lower_edge
    - brightness_center
    - brightness_mean
    - brightness_std
    - estimated_upper_edge_variance
    - estimated_lower_edge_variance
    - estimated_slope_variance
    - trolley_end_reason
    - mask_edgelog_1
    - mask_edgelog_2
  columns_list:
    - image_idx
    - ix
    - measurement_area
    - camera_num
    - image_name
    - trolley_id
    - measured_upper_edge
    - measured_lower_edge
    - estimated_upper_edge
    - estimated_lower_edge
    - estimated_width
    - estimated_width_std
    - brightness_center
    - brightness_mean
    - brightness_std
    - estimated_slope    # pixel
    - upper_boundary    # pixel
    - lower_boundary    # pixel
    - estimated_upper_edge_variance    # kalman
    - estimated_lower_edge_variance    # kalman
    - estimated_slope_variance    # kalman
    - trolley_end_reason
    - mask_edgelog_1
    - mask_edgelog_2
  csv_dtype:
    image_idx: int32
    ix: int32
    measurement_area: str
    camera_num: str
    image_name: str
    trolley_id: str
    measured_upper_edge: float32
    measured_lower_edge: float32
    estimated_upper_edge: float32
    estimated_lower_edge: float32
    estimated_width: float32
    estimated_width_std: float32
    brightness_center: float32
    brightness_mean: float32
    brightness_std: float32
    estimated_slope: float32
    upper_boundary: float32
    lower_boundary: float32
    estimated_upper_edge_variance: float32
    estimated_lower_edge_variance: float32
    estimated_slope_variance: float32
    trolley_end_reason: str
    mask_edgelog_1: float32
    mask_edgelog_2: float32

format_func:
  camera_name_to_type:
    高(左): HD11
    高(右): HD12
    中(左): HD21
    中(右): HD22
    低(左): HD31
    低(右): HD32
  rail_names:
    Chuo: 中央線
    ChuoKanko: 中央緩行線
    Yamate: 山手線
    Utsunomiya: 宇都宮線
    Kawagoe: 川越線
    Takasaki: 高崎線
  station_names:
    st: 構内
    Omiya: 大宮
    Nisshin: 日進
    Nishioomiya: 西大宮
    Sashiougi: 指扇
    Minamifuruya: 南古谷
    Miyahara: 宮原
    Ageo: 上尾
    Kitaageo: 北上尾
    Okegawa: 桶川
    Kitamoto: 北本
    Kounosu: 鴻巣
    Kitakounosu: 北鴻巣
    Fukiage: 吹上
    Gyouda: 行田
    Kumagaya: 熊谷
    KumagayaFT: 熊谷貨物タ
    Kagohara: 籠原
    Fukaya: 深谷
    Okabe: 岡部
    Honjo: 本庄
    Jinbohara: 神保原
    Shinmachi: 新町
    Kitafujioka: 北藤岡
    Kuragano: 倉賀野
    TakasakiSY: 高崎操
    Takasaki: 高崎
    Tokyo: 東京
    Kanda: 神田
    Ochanomizu: 御茶ノ水
    Suidobashi: 水道橋
    Iidabashi: 飯田橋
    Ichigaya: 市ヶ谷
    Yotsuya: 四ツ谷
    Shinanomachi: 信濃町
    Sendagaya: 千駄ヶ谷
    Yoyogi: 代々木
    Shinjuku: 新宿
    Ookubo: 大久保
    Higashinakano: 東中野
    Nakano: 中野
    Koenji: 高円寺
    Asagaya: 阿佐ヶ谷
    Ogikubo: 荻窪
    Nishiogikubo: 西荻窪
    Kichijoji: 吉祥寺
    Ueno: 上野
    Nippori: 日暮里
    Tabata: 田端
    Yurakucho: 有楽町
    Shinbashi: 新橋
    Hamamatsucho: 浜松町
    Tamachi: 田町
    Shinagawa: 品川
    Oosaki: 大崎
    Akihabara: 秋葉原
    Okachimachi: 御徒町
    Nishinippori: 西日暮里
    Komagome: 駒込
    Sugamo: 巣鴨
    Ootsuka: 大塚
    Ikebukuro: 池袋
    Mejiro: 目白
    Takadanobaba: 高田馬場
    Shinookubo: 新大久保
    Harajuku: 原宿
    Shibuya: 渋谷
    Ebisu: 恵比寿
    Meguro: 目黒
    Gotanda: 五反田
  rail_type_names:
    up: 上り
    down: 下り
    soto: 外回り
    uchi: 内回り
  time_band_names:
    day: 昼間
    knight: 夜間

measurement:
  missing_threshold: 5
  brightness_diff_threshold: 255
  sharpness_threshold: 1
  missing_count_limit: 100
  width_exceed_limit: 60

results:
  max_len: 1000
