services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: esio-cis
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro # AWS認証情報ファイルをマウント（読み取り専用）
    environment:
      - PYTHONPATH=/app
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-northeast-1}
    restart: always
