[theme]
primaryColor = "#ff9900"
backgroundColor = "#fff9f0"
secondaryBackgroundColor = "#f8f8f8"
textColor = "#333333"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false