# デバッグモード（trueで有効化）
debug = false

# AWS 認証用の設定
[cognito]
client_id = "65i8j36idrecf6bqr86qlgtaui"
client_secret = "v0ts3bg4nm2mm9iernjt87r5no2rvnhcb95rqmqsbh4tkbq1vfi"
aws_region = "ap-northeast-1"
user_pool_id = "ap-northeast-1_OPZscsccQ"
domain = "https://opzscsccq.auth.ap-northeast-1.amazoncognito.com"
redirect_uri = "https://esio-cis.com"